"""Documentation pins for the ``reference_standards`` field (IC-05, AC-15 area).

The field + MVP format live in the ``conventions`` rule (the tracked source of
the generated ``conventions`` skill copies) and the default-strip / keep opt-in
policy lives in ``docs/providers/multi-provider.md``.

The provider skill copies are generated by ``sync.py`` and gitignored, so the
test always pins the tracked rule source and only additionally checks the
copies that exist in a synced working tree (OQ-8).

Run: python -m pytest tests/test_reference_standards_documented.py -v
"""
from __future__ import annotations

import sys
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO_ROOT / "scripts"))

from lib.consistency.reference_standards import REFERENCE_STANDARDS_FORMAT_HINT  # noqa: E402

CONVENTIONS_SOURCE = _REPO_ROOT / "rules" / "2-platform" / "agent-meta-conventions.md"

CONVENTIONS_COPIES = (
    _REPO_ROOT / ".claude" / "skills" / "conventions" / "SKILL.md",
    _REPO_ROOT / ".opencode" / "skills" / "conventions" / "SKILL.md",
    _REPO_ROOT / ".gemini" / "rules" / "conventions.md",
)

PROVIDER_DOC = _REPO_ROOT / "docs" / "providers" / "multi-provider.md"

_AGREEING_SENTENCE = "stripped from every generated provider"


def _existing_copies() -> list[Path]:
    return [p for p in CONVENTIONS_COPIES if p.exists()]


def test_conventions_skill_documents_field_and_format():
    """The tracked conventions-rule source names the field and the MVP format."""
    text = CONVENTIONS_SOURCE.read_text(encoding="utf-8")
    assert "reference_standards" in text
    assert REFERENCE_STANDARDS_FORMAT_HINT in text


def test_multi_provider_documents_default_strip_and_keep_opt_in():
    """IC-05: default strip + config-only keep opt-in are documented."""
    text = PROVIDER_DOC.read_text(encoding="utf-8")
    assert "reference_standards" in text
    assert "frontmatter-keep-fields" in text
    assert "frontmatter_keep_fields" in text
    assert "keep schlägt strip" in text
    assert "gestrippt" in text


def test_all_conventions_skill_copies_agree():
    """OQ-8: every generated copy (if present) carries the same field sentence.

    The copies are gitignored sync output, so a fresh (unsynced) checkout has
    none — the tracked rule source is pinned by the other test above."""
    copies = _existing_copies()
    if not copies:
        pytest.skip("no generated conventions skill copies (unsynced checkout)")
    for copy in copies:
        text = copy.read_text(encoding="utf-8")
        assert "reference_standards" in text, copy
        assert REFERENCE_STANDARDS_FORMAT_HINT in text, copy
        assert _AGREEING_SENTENCE in text, copy
