"""Stale-cleanup regression tests for mcp-*.md / tool-*.md rule files.

Mirrors rules.py::sync_rules()'s previously_managed/now_managed diff pattern
(scripts/lib/rule_index.py), but scoped to mcp.py's and external_tools.py's
own independent write loops and their own ".agent-meta-managed-mcp" /
".agent-meta-managed-tools" sidecar indexes.
"""

from pathlib import Path

import yaml

from scripts.lib.external_tools import generate_external_tool_artifacts
from scripts.lib.log import SyncLog
from scripts.lib.mcp import generate_mcp_artifacts


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


# ---------------------------------------------------------------------------
# mcp.py: mcp-<server>.md stale cleanup
# ---------------------------------------------------------------------------

def _write_mcp_registry(agent_meta_root: Path, servers: dict) -> None:
    _write(
        agent_meta_root / "config" / "mcp-registry.yaml",
        yaml.dump({"mcp-servers": servers}),
    )


def test_mcp_rule_file_removed_when_server_deactivated(tmp_path):
    agent_meta_root = tmp_path / "agent-meta"
    project_root = tmp_path / "project"
    _write_mcp_registry(agent_meta_root, {
        "honcho": {"description": "honcho"},
        "reqflow": {"description": "reqflow"},
    })
    provider_config = {"Claude": {"has_rules": True}}

    # First sync: both servers active.
    generate_mcp_artifacts(
        agent_meta_root, project_root, {"mcp-servers": ["honcho", "reqflow"], "platforms": []},
        provider_config, SyncLog(), dry_run=False, provider="Claude",
    )
    honcho_rule = project_root / ".claude" / "rules" / "mcp-honcho.md"
    reqflow_rule = project_root / ".claude" / "rules" / "mcp-reqflow.md"
    assert honcho_rule.exists()
    assert reqflow_rule.exists()
    index_path = project_root / ".claude" / "rules" / ".agent-meta-managed-mcp"
    assert index_path.exists()
    assert set(index_path.read_text(encoding="utf-8").split()) == {"mcp-honcho.md", "mcp-reqflow.md"}

    # Second sync: reqflow removed from project.yaml's active list.
    generate_mcp_artifacts(
        agent_meta_root, project_root, {"mcp-servers": ["honcho"], "platforms": []},
        provider_config, SyncLog(), dry_run=False, provider="Claude",
    )
    assert honcho_rule.exists()
    assert not reqflow_rule.exists()
    assert set(index_path.read_text(encoding="utf-8").split()) == {"mcp-honcho.md"}


def test_mcp_rule_file_removed_when_server_deleted_from_registry(tmp_path):
    agent_meta_root = tmp_path / "agent-meta"
    project_root = tmp_path / "project"
    _write_mcp_registry(agent_meta_root, {"honcho": {"description": "honcho"}, "reqflow": {"description": "reqflow"}})
    provider_config = {"Claude": {"has_rules": True}}
    config = {"mcp-servers": ["honcho", "reqflow"], "platforms": []}

    generate_mcp_artifacts(agent_meta_root, project_root, config, provider_config, SyncLog(), dry_run=False, provider="Claude")
    assert (project_root / ".claude" / "rules" / "mcp-reqflow.md").exists()

    # Registry itself drops the server entirely (not just deactivated).
    _write_mcp_registry(agent_meta_root, {"honcho": {"description": "honcho"}})
    generate_mcp_artifacts(agent_meta_root, project_root, config, provider_config, SyncLog(), dry_run=False, provider="Claude")
    assert not (project_root / ".claude" / "rules" / "mcp-reqflow.md").exists()


def test_mcp_rule_file_bootstrap_sweeps_legacy_orphan_without_prior_index(tmp_path):
    # Simulates the real-world repo state this feature was built to fix:
    # a mcp-reqflow.md rule file already exists on disk (generated by an
    # older sync before this stale-cleanup mechanism existed) but there is
    # no ".agent-meta-managed-mcp" index yet to diff against.
    agent_meta_root = tmp_path / "agent-meta"
    project_root = tmp_path / "project"
    _write_mcp_registry(agent_meta_root, {"honcho": {"description": "honcho"}})
    provider_config = {"Claude": {"has_rules": True}}

    orphan_path = project_root / ".claude" / "rules" / "mcp-reqflow.md"
    _write(
        orphan_path,
        "# MCP: reqflow\n\nstale leftover\n\n---\n\n"
        "*Generiert von agent-meta aus `config/mcp-registry.yaml` — nicht manuell bearbeiten.*\n",
    )
    assert not (project_root / ".claude" / "rules" / ".agent-meta-managed-mcp").exists()

    generate_mcp_artifacts(
        agent_meta_root, project_root, {"mcp-servers": ["honcho"], "platforms": []},
        provider_config, SyncLog(), dry_run=False, provider="Claude",
    )

    assert not orphan_path.exists()
    assert (project_root / ".claude" / "rules" / "mcp-honcho.md").exists()


def test_mcp_bootstrap_does_not_sweep_unrelated_file_sharing_mcp_prefix(tmp_path):
    # Regression test: rules/1-generic/mcp-guardrails.md is a plain,
    # manually-authored rule that happens to share the "mcp-" filename
    # prefix with generated mcp-<server>.md rule files. A naive glob-only
    # bootstrap (no content-marker check) would misidentify it as a legacy
    # orphan on the very first sync and delete it — it must survive.
    agent_meta_root = tmp_path / "agent-meta"
    project_root = tmp_path / "project"
    _write_mcp_registry(agent_meta_root, {"honcho": {"description": "honcho"}})
    provider_config = {"Claude": {"has_rules": True}}

    guardrails_path = project_root / ".claude" / "rules" / "mcp-guardrails.md"
    _write(guardrails_path, "# MCP Hard Prohibitions\n\nManually authored, not agent-meta-generated.\n")

    generate_mcp_artifacts(
        agent_meta_root, project_root, {"mcp-servers": ["honcho"], "platforms": []},
        provider_config, SyncLog(), dry_run=False, provider="Claude",
    )

    assert guardrails_path.exists()
    assert (project_root / ".claude" / "rules" / "mcp-honcho.md").exists()


def test_mcp_stale_cleanup_dry_run_does_not_delete(tmp_path):
    agent_meta_root = tmp_path / "agent-meta"
    project_root = tmp_path / "project"
    _write_mcp_registry(agent_meta_root, {"honcho": {"description": "honcho"}, "reqflow": {"description": "reqflow"}})
    provider_config = {"Claude": {"has_rules": True}}
    config = {"mcp-servers": ["honcho", "reqflow"], "platforms": []}

    generate_mcp_artifacts(agent_meta_root, project_root, config, provider_config, SyncLog(), dry_run=False, provider="Claude")
    reqflow_rule = project_root / ".claude" / "rules" / "mcp-reqflow.md"
    assert reqflow_rule.exists()

    generate_mcp_artifacts(
        agent_meta_root, project_root, {"mcp-servers": ["honcho"], "platforms": []},
        provider_config, SyncLog(), dry_run=True, provider="Claude",
    )
    # dry_run must never touch the filesystem.
    assert reqflow_rule.exists()


# ---------------------------------------------------------------------------
# external_tools.py: tool-<name>.md stale cleanup
# ---------------------------------------------------------------------------

def _write_tools_registry(agent_meta_root: Path, tools: dict) -> None:
    _write(
        agent_meta_root / "config" / "external-tools-registry.yaml",
        yaml.dump({"external-tools": tools}),
    )


def test_tool_rule_file_removed_when_tool_deactivated(tmp_path):
    agent_meta_root = tmp_path / "agent-meta"
    project_root = tmp_path / "project"
    _write_tools_registry(agent_meta_root, {
        "graphify": {"enabled-by-default": True, "rule-content": "body-a"},
        "otherctl": {"enabled-by-default": True, "rule-content": "body-b"},
    })
    provider_config = {"Claude": {"has_rules": True}}

    generate_external_tool_artifacts(
        agent_meta_root, project_root, {}, provider_config, SyncLog(), dry_run=False, provider="Claude",
    )
    graphify_rule = project_root / ".claude" / "rules" / "tool-graphify.md"
    otherctl_rule = project_root / ".claude" / "rules" / "tool-otherctl.md"
    assert graphify_rule.exists()
    assert otherctl_rule.exists()
    index_path = project_root / ".claude" / "rules" / ".agent-meta-managed-tools"
    assert set(index_path.read_text(encoding="utf-8").split()) == {"tool-graphify.md", "tool-otherctl.md"}

    # Deactivate otherctl explicitly via project config.
    config = {"external-tools": {"otherctl": {"enabled": False}}}
    generate_external_tool_artifacts(
        agent_meta_root, project_root, config, provider_config, SyncLog(), dry_run=False, provider="Claude",
    )
    assert graphify_rule.exists()
    assert not otherctl_rule.exists()
    assert set(index_path.read_text(encoding="utf-8").split()) == {"tool-graphify.md"}


def test_tool_rule_file_bootstrap_sweeps_legacy_orphan_without_prior_index(tmp_path):
    agent_meta_root = tmp_path / "agent-meta"
    project_root = tmp_path / "project"
    _write_tools_registry(agent_meta_root, {"graphify": {"enabled-by-default": True, "rule-content": "body"}})
    provider_config = {"Claude": {"has_rules": True}}

    orphan_path = project_root / ".claude" / "rules" / "tool-legacyctl.md"
    _write(
        orphan_path,
        "# External Tool: legacyctl\n\nstale leftover\n\n---\n\n"
        "*Generiert von agent-meta aus `config/external-tools-registry.yaml` — "
        "nicht manuell bearbeiten.*\n",
    )

    generate_external_tool_artifacts(
        agent_meta_root, project_root, {}, provider_config, SyncLog(), dry_run=False, provider="Claude",
    )

    assert not orphan_path.exists()
    assert (project_root / ".claude" / "rules" / "tool-graphify.md").exists()


def test_tool_stale_cleanup_dry_run_does_not_delete(tmp_path):
    agent_meta_root = tmp_path / "agent-meta"
    project_root = tmp_path / "project"
    _write_tools_registry(agent_meta_root, {
        "graphify": {"enabled-by-default": True, "rule-content": "body-a"},
        "otherctl": {"enabled-by-default": True, "rule-content": "body-b"},
    })
    provider_config = {"Claude": {"has_rules": True}}

    generate_external_tool_artifacts(
        agent_meta_root, project_root, {}, provider_config, SyncLog(), dry_run=False, provider="Claude",
    )
    otherctl_rule = project_root / ".claude" / "rules" / "tool-otherctl.md"
    assert otherctl_rule.exists()

    config = {"external-tools": {"otherctl": {"enabled": False}}}
    generate_external_tool_artifacts(
        agent_meta_root, project_root, config, provider_config, SyncLog(), dry_run=True, provider="Claude",
    )
    assert otherctl_rule.exists()
