"""Problem-1 end-to-end integration regression (B-I / B-II / B-III).

Trace anchor: ``SPEC-STALE-ROLE-CLEANUP-2026-09-13`` (APPROVED 2026-09-13),
acceptance criteria AC-03, AC-10, AC-15, AC-16 and AC-21 of
``docs/specs/2026-09-13-stale-role-cleanup-design.md``.

This is the explicit **real-fixture** end-to-end check: one temporary project,
synced twice by the real ``python scripts/sync.py`` CLI (offline, deterministic,
no network). Unlike the focused unit suites (``test_agent_sync_helpers.py``,
``test_cleanup_preview_cli.py``, ``test_context_managed_block_shrink.py``) it
proves all three Problem-1 behaviours **together** against the same project
state, which is exactly the state transition a real consumer goes through:

1. **Foreign role survives a MISSING managed index** (B-I, AC-03/AC-15/AC-21).
   A hand-authored role file is pre-seeded in ``.claude/agents/`` before the
   first sync, with **no** ``.agent-meta-managed`` index present. The first sync
   must be fail-closed: the foreign file survives byte-identically and is never
   backed up or listed in the freshly written index.
2. **Stale role is cleaned via preview -> apply** (B-I/B-II, AC-01/AC-10). A role
   removed from ``roles:`` is reported stale by ``--cleanup-preview`` (with the
   preview asserted to be mutation-free), then removed by the applying sync,
   backup-first. The foreign file never enters the deletion set.
3. **Managed block shrinks** (B-III, AC-16). Removing that role from the hint
   source (``roles:``) removes its literal row from the ``AGENTS.md`` managed
   block on the next sync, while the surrounding static content and the
   remaining role rows are preserved.

Provider-agnostic: the fixture names providers only as *config values*
(``ai-providers:``) and the test never branches on a provider name. The
``AGENTS.md`` subject is used because the Gemini path renders the per-role hint
table inside the managed block; the Claude path uses the dedicated
``AGENT_HINTS_CLAUDE`` entry-point hint instead. Both are config-driven.

Placement: a new Python test (following the existing real-sync e2e precedent
``test_generated_file_drift_e2e.py``) rather than an extension of scenario
``62-stale-role-cleanup``. ``tests/scenarios/run.sh`` always performs a first
real sync *before* the per-scenario assert runs, so the shell harness
structurally cannot express behaviour 1's required "no index at the first sync"
pre-state; the Python fixture controls both syncs and the exact in-between
state. Scenario 62 keeps covering the single-post-sync preview/apply/foreign
path.
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]
_SYNC_PY = _REPO_ROOT / "scripts" / "sync.py"

_MANAGED_BLOCK_RE = re.compile(
    r"<!--\s*agent-meta:managed-begin\s*-->.*?<!--\s*agent-meta:managed-end\s*-->",
    re.DOTALL,
)

_FOREIGN_BODY = (
    "---\n"
    "name: hand-authored-role\n"
    "---\n"
    "Hand-authored role file, never generated by agent-meta.\n"
)

_STALE_ROLE = "code-reviewer"


def _run_sync(project_root: Path, *extra_args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [
            sys.executable,
            str(_SYNC_PY),
            "--config",
            str(project_root / ".meta-config" / "project.yaml"),
            *extra_args,
        ],
        capture_output=True,
        text=True,
        cwd=str(project_root),
        timeout=180,
    )


def _write_project_yaml(project_root: Path, roles: list[str]) -> None:
    meta = project_root / ".meta-config"
    meta.mkdir(parents=True, exist_ok=True)
    role_lines = "".join(f"- {role}\n" for role in roles)
    (meta / "project.yaml").write_text(
        "agent-meta-version: 0.101.0\n"
        "ai-providers: [Claude, Gemini]\n"
        "dod-preset: rapid-prototyping\n"
        "roles:\n"
        f"{role_lines}"
        "project:\n"
        "  name: problem1-integration\n"
        "  prefix: p1\n"
        "  short: problem1\n"
        "variables:\n"
        "  PROJECT_NAME: problem1-integration\n"
        "  PROJECT_DESCRIPTION: Problem-1 end-to-end integration fixture.\n"
        "  PROJECT_GOAL: Prove foreign survival, stale cleanup and block shrink.\n"
        "  GIT_PLATFORM: GitHub\n"
        "  GIT_REMOTE_URL: https://github.com/example/problem1-integration\n"
        "  GIT_MAIN_BRANCH: main\n"
        "rules-preset: default\n"
        "speech-mode: full\n"
        "tier-preset: Normal\n"
        "max-parallel-agents: 2\n"
        "conventions-preset: default\n",
        encoding="utf-8",
    )


def _split_around_managed_block(text: str) -> tuple[str, str, str]:
    match = _MANAGED_BLOCK_RE.search(text)
    assert match is not None, "no agent-meta managed block found"
    return text[: match.start()], match.group(0), text[match.end():]


def test_problem1_foreign_survives_stale_cleanup_and_block_shrink(tmp_path: Path) -> None:
    """One real temp project, two real syncs: all three Problem-1 behaviours."""
    project_root = tmp_path / "project"

    # --- Fixture: a legacy first-sync state --------------------------------
    # A provider agents dir with a hand-authored role and NO managed index.
    _write_project_yaml(
        project_root, ["orchestrator", "developer", _STALE_ROLE, "git"]
    )
    agents_dir = project_root / ".claude" / "agents"
    agents_dir.mkdir(parents=True)
    foreign = agents_dir / "hand-authored-role.md"
    foreign.write_text(_FOREIGN_BODY, encoding="utf-8")
    index = agents_dir / ".agent-meta-managed"
    assert not index.exists(), "fixture precondition: no managed index before the first sync"

    # --- Behaviour 1: fail-closed first sync keeps the foreign role ---------
    first = _run_sync(project_root)
    assert first.returncode == 0, first.stderr
    assert foreign.is_file(), (
        "foreign role was deleted although no managed index existed — "
        "fail-open regression (AC-03/AC-15)"
    )
    assert foreign.read_text(encoding="utf-8") == _FOREIGN_BODY
    assert list(agents_dir.glob("hand-authored-role.md.sync-backup-*")) == []
    assert index.is_file(), "sync must write the managed index"
    index_after_first = index.read_text(encoding="utf-8")
    assert f"{_STALE_ROLE}.md" in index_after_first
    assert "hand-authored-role.md" not in index_after_first

    # Snapshot the AGENTS.md managed block before the role is removed.
    agents_md = project_root / "AGENTS.md"
    assert agents_md.is_file()
    prefix_before, block_before, _ = _split_around_managed_block(
        agents_md.read_text(encoding="utf-8")
    )
    assert f"| `{_STALE_ROLE}` |" in block_before
    assert "| `developer` |" in block_before

    # --- Remove one role from the config (the hint source) ------------------
    _write_project_yaml(project_root, ["orchestrator", "developer", "git"])

    # --- Behaviour 2a: preview reports the stale role, mutation-free --------
    preview = _run_sync(project_root, "--cleanup-preview")
    assert preview.returncode == 0, preview.stderr
    payload = json.loads(preview.stdout)
    assert payload["version"] == 1
    providers = {entry["provider"]: entry for entry in payload["providers"]}
    assert "Claude" in providers

    claude = providers["Claude"]
    stale_by_path = {entry["path"]: entry for entry in claude["stale"]}
    foreign_by_path = {entry["path"]: entry for entry in claude["foreign"]}

    stale_rel = f".claude/agents/{_STALE_ROLE}.md"
    foreign_rel = ".claude/agents/hand-authored-role.md"
    assert stale_rel in stale_by_path, sorted(stale_by_path)
    assert stale_by_path[stale_rel]["reason"] == "role removed from config"
    assert stale_by_path[stale_rel]["tracked"] is True
    assert stale_by_path[stale_rel]["adopted"] is False
    assert foreign_rel in foreign_by_path, sorted(foreign_by_path)
    assert foreign_by_path[foreign_rel]["legacy_unmarked"] is True

    # The foreign file never enters the deletion set (stale paths only).
    deletion_set = set(stale_by_path)
    assert foreign_rel not in deletion_set
    assert stale_rel not in foreign_by_path

    # Preview must not mutate the filesystem (AC-10 / F-04).
    assert (agents_dir / f"{_STALE_ROLE}.md").is_file()
    assert foreign.read_text(encoding="utf-8") == _FOREIGN_BODY
    assert index.read_text(encoding="utf-8") == index_after_first
    assert list(agents_dir.glob("*.sync-backup-*")) == []

    # --- Behaviour 2b: apply removes the stale role backup-first ------------
    stale_file = agents_dir / f"{_STALE_ROLE}.md"
    stale_content = stale_file.read_text(encoding="utf-8")
    apply_result = _run_sync(project_root)
    assert apply_result.returncode == 0, apply_result.stderr

    assert not stale_file.exists(), "apply did not remove the stale role"
    backups = list(agents_dir.glob(f"{_STALE_ROLE}.md.sync-backup-*"))
    assert len(backups) == 1, backups
    assert backups[0].read_text(encoding="utf-8") == stale_content
    assert f"{_STALE_ROLE}.md" not in index.read_text(encoding="utf-8")
    assert foreign.is_file(), "apply removed the foreign role"
    assert foreign.read_text(encoding="utf-8") == _FOREIGN_BODY

    # --- Behaviour 3: managed block shrank, surrounding content preserved ---
    prefix_after, block_after, _ = _split_around_managed_block(
        agents_md.read_text(encoding="utf-8")
    )
    assert f"| `{_STALE_ROLE}` |" not in block_after, "stale hint row still in managed block"
    assert "| `developer` |" in block_after
    assert "| `orchestrator` |" in block_after
    assert len(block_after) < len(block_before), "managed block did not shrink"
    assert prefix_after == prefix_before, "content outside the managed block changed"
