"""Environment variable management: project.yaml → platform-specific scripts.

Public interface:
    load_env_config(config)        → dict of env var definitions from project.yaml
    generate_env_scripts(config, dry_run) → generate env.ps1 / env.sh / unset scripts
    update_env_var(config, name, value)   → update/remove env var in memory
"""

from pathlib import Path

ENV_DIR = ".meta-config"
SET_PS1 = f"{ENV_DIR}/env.ps1"
SET_SH = f"{ENV_DIR}/env.sh"
UNSET_PS1 = f"{ENV_DIR}/env.unset.ps1"
UNSET_SH = f"{ENV_DIR}/env.unset.sh"


def load_env_config(config: dict) -> dict:
    """Return the environments dict from project.yaml (empty dict if absent)."""
    envs = config.get("environments")
    if isinstance(envs, dict):
        return envs
    return {}


def _generate_powershell_set(envs: dict) -> str:
    lines = [
        "<#",
        "  Environment Setup Script — generated by agent-meta",
        "  Source: .meta-config/project.yaml → environments:",
        "  Run: . .meta-config/env.ps1  (dot-source to persist in session)",
        "  Unset: . .meta-config/env.unset.ps1",
        "#>",
        "",
    ]
    for name, cfg in sorted(envs.items()):
        desc = cfg.get("description", name)
        default = cfg.get("default", "")
        required = cfg.get("required", False)
        secret = cfg.get("secret", False)
        tag = ""
        if required:
            tag = " [REQUIRED]"
        if secret:
            tag += " [SECRET]"
        lines.append(f"# {desc}{tag}")
        lines.append(f"if (-not (Test-Path env:{name})) {{")
        if default:
            display = _mask(default) if secret else default
            lines.append(f'    Write-Host "  + {name}={display} (default)"')
            lines.append(f'    $env:{name} = "{default}"')
        else:
            lines.append(f'    Write-Host "  !  {name}=<not set> (set in project.yaml or env)"')
            lines.append(f'    $env:{name} = ""')
        lines.append("} else {")
        display_default = _mask(f"$env:{name}") if secret else f"$env:{name}"
        lines.append(f'    Write-Host "  i  {name} already set"')
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def _generate_powershell_unset(envs: dict) -> str:
    lines = [
        "<#",
        "  Environment Unset Script — generated by agent-meta",
        "  Removes all environment variables managed by project.yaml.",
        "  Run: . .meta-config/env.unset.ps1  (dot-source to affect session)",
        "#>",
        "",
    ]
    for name in sorted(envs.keys()):
        lines.append(f"Remove-Item env:{name} -ErrorAction SilentlyContinue")
        lines.append(f'Write-Host "  -  {name}"')
    return "\n".join(lines)


def _generate_bash_set(envs: dict) -> str:
    lines = [
        "# Environment Setup Script — generated by agent-meta",
        "# Source: .meta-config/project.yaml → environments:",
        "# Run: source .meta-config/env.sh",
        "# Unset: source .meta-config/env.unset.sh",
        "",
    ]
    for name, cfg in sorted(envs.items()):
        desc = cfg.get("description", name)
        default = cfg.get("default", "")
        required = cfg.get("required", False)
        secret = cfg.get("secret", False)
        tag = ""
        if required:
            tag = " [REQUIRED]"
        if secret:
            tag += " [SECRET]"
        lines.append(f"# {desc}{tag}")
        if default:
            display = _mask(default) if secret else default
            lines.append(f'if [ -z "${{{name}}}" ]; then')
            lines.append(f'    echo "  + {name}={display} (default)"')
            lines.append(f'    export {name}="{default}"')
            lines.append("else")
            lines.append(f'    echo "  i  {name} already set"')
            lines.append("fi")
        else:
            lines.append(f'if [ -z "${{{name}}}" ]; then')
            lines.append(f'    echo "  !  {name}=<not set> (set in project.yaml or env)"')
            lines.append(f'    export {name}=""')
            lines.append("else")
            lines.append(f'    echo "  i  {name} already set"')
            lines.append("fi")
        lines.append("")
    return "\n".join(lines)


def _generate_bash_unset(envs: dict) -> str:
    lines = [
        "# Environment Unset Script — generated by agent-meta",
        "# Removes all environment variables managed by project.yaml.",
        "# Run: source .meta-config/env.unset.sh",
        "",
    ]
    for name in sorted(envs.keys()):
        lines.append(f"unset {name} 2>/dev/null")
        lines.append(f'echo "  -  {name}"')
    return "\n".join(lines)


def _mask(value: str) -> str:
    """Mask secret values in logs: keep first 4 and last 4 chars."""
    clean = str(value).strip()
    if len(clean) <= 8:
        return "*" * len(clean)
    return clean[:4] + "*" * (len(clean) - 8) + clean[-4:]


def generate_env_scripts(config: dict, project_root: Path, dry_run: bool = False) -> dict:
    """Generate platform-specific env scripts from project.yaml environments section.

    Returns a dict with script status per file: {'.meta-config/env.ps1': 'created'|'skipped', ...}
    """
    from .io import is_unchanged

    envs = load_env_config(config)

    scripts = {
        SET_PS1: _generate_powershell_set(envs),
        SET_SH: _generate_bash_set(envs),
        UNSET_PS1: _generate_powershell_unset(envs),
        UNSET_SH: _generate_bash_unset(envs),
    }

    results: dict = {}
    for rel_path, content in scripts.items():
        target = project_root / rel_path
        if dry_run:
            results[rel_path] = "dry-run"
            continue
        if is_unchanged(target, content):
            results[rel_path] = "skipped"
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        results[rel_path] = "created"

    return results


def update_env_var(config: dict, name: str, definition: dict | None) -> dict:
    """Update or remove an environment variable definition in the config dict.

    name: env var name (uppercase, e.g. MCP_HONCHO_URL)
    definition: dict with keys: description, default, required, secret.
                Pass None to REMOVE the env var from config.
    """
    if "environments" not in config:
        config["environments"] = {}

    if definition is None:
        config["environments"].pop(name, None)
    else:
        config["environments"][name] = {
            "description": definition.get("description", ""),
            "default": definition.get("default", ""),
            "required": bool(definition.get("required", False)),
            "secret": bool(definition.get("secret", False)),
        }

    return config
