"""Schema utilities — auto-generation of derived schema fields.

The `properties.roles.items.enum` list in `config/project-config.schema.json`
is derived from `config/role-defaults.yaml`. Keeping it in sync manually has
caused drift (missing roles). This module regenerates the enum at every
`sync.py` run from the canonical role map.
"""
from __future__ import annotations

import json
from pathlib import Path

from .log import SyncLog
from .roles import build_role_map


SCHEMA_PATH = "config/project-config.schema.json"
ENUM_COMMENT = (
    "Auto-generated by sync.py from config/role-defaults.yaml "
    "— do not edit manually"
)


def update_roles_enum(
    agent_meta_root: Path,
    log: SyncLog | None = None,
    dry_run: bool = False,
) -> int:
    """Update `properties.roles.items.enum` in the project-config schema.

    Reads the canonical role list from `config/role-defaults.yaml` via
    `build_role_map()` and writes the sorted list into the schema's roles enum.
    Adds a `$comment` field signalling that the enum is auto-generated.

    Args:
        agent_meta_root: Absolute path to the agent-meta repository root.
        log: Optional SyncLog for structured output. If None, falls back to
            silent operation (used in tests).
        dry_run: If True, do not write to disk. Still computes and logs the
            intended action.

    Returns:
        The number of roles written to (or that would be written to) the enum.
        Returns 0 if the schema file or expected JSON path is missing.
    """
    schema_path = agent_meta_root / SCHEMA_PATH

    if not schema_path.exists():
        if log is not None:
            log.warn(f"schema: not found at {schema_path} — skipping enum update")
        return 0

    roles = sorted(build_role_map(agent_meta_root).keys())

    try:
        with schema_path.open("r", encoding="utf-8") as f:
            schema = json.load(f)
    except (json.JSONDecodeError, OSError) as exc:
        if log is not None:
            log.warn(f"schema: failed to read {schema_path}: {exc}")
        return 0

    try:
        items = schema["properties"]["roles"]["items"]
    except (KeyError, TypeError):
        if log is not None:
            log.warn(
                "schema: properties.roles.items not found in "
                f"{SCHEMA_PATH} — skipping enum update"
            )
        return 0

    if "enum" not in items:
        if log is not None:
            log.warn(
                "schema: properties.roles.items has no 'enum' key "
                "— skipping enum update"
            )
        return 0

    # Skip write if nothing changed (avoid noisy diffs / unnecessary I/O)
    current = items.get("enum")
    current_comment = items.get("$comment")
    if current == roles and current_comment == ENUM_COMMENT:
        if log is not None:
            log.skip(SCHEMA_PATH, f"roles enum already up to date ({len(roles)} roles)")
        return len(roles)

    items["enum"] = roles
    items["$comment"] = ENUM_COMMENT

    if dry_run:
        if log is not None:
            log.action(
                "schema",
                SCHEMA_PATH,
                f"would update roles enum ({len(roles)} roles)",
            )
        return len(roles)

    try:
        with schema_path.open("w", encoding="utf-8") as f:
            json.dump(schema, f, indent=2, ensure_ascii=False)
            f.write("\n")
    except OSError as exc:
        if log is not None:
            log.warn(f"schema: failed to write {schema_path}: {exc}")
        return 0

    if log is not None:
        log.action("schema", SCHEMA_PATH, f"updated roles enum ({len(roles)} roles)")
    return len(roles)
