#!/usr/bin/env python3
"""Generate the canonical promptfoo config from the eval catalogs (#535).

Single source of truth (finding W3): the YAML catalogs under
tests/routing-llm-eval/ remain the only hand-maintained place. This script
derives promptfooconfig.generated.yaml from them, so CI-promptfoo and the
local bash runner consume the same cases without drift.

Finding W4: provider commands deliberately contain NO {{prompt}} placeholder.
promptfoo appends the rendered prompt as the last argument when the command
string lacks a placeholder, which keeps multi-line prompts out of shell
quoting hell.

Usage:
    python3 gen_promptfoo_config.py            # write generated file
    python3 gen_promptfoo_config.py --check    # exit 1 if it would change

Idempotency is enforced by tests/test_agent_eval_framework.py.
"""
from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("PyYAML is required (pip install pyyaml).", file=sys.stderr)
    sys.exit(1)

DIR = Path(__file__).resolve().parents[1] / "tests" / "routing-llm-eval"
OUT = DIR / "promptfooconfig.generated.yaml"

CATALOGS = [
    DIR / "catalog.generated.yaml",
    DIR / "catalog.manual.yaml",
    DIR / "catalog.behavior.yaml",
]

PROVIDERS = [
    {"id": "exec", "label": "claude-orchestrator", "command": ["./provider-claude.sh"]},
    {"id": "exec", "label": "opencode-orchestrator", "command": ["./provider-opencode.sh"]},
]


def build() -> dict:
    tests = []
    for path in CATALOGS:
        if not path.exists():
            continue
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        for case in data.get("cases", []):
            role = case.get("role") or "orchestrator"
            task = case.get("prompt") or case.get("task", "")
            asserts = []
            if case.get("expected"):
                asserts.append({"type": "equals-any", "value": list(map(str, case["expected"]))})
            if case.get("expected_any"):
                asserts.append({"type": "icontains-any", "value": list(map(str, case["expected_any"]))})
            for lit in case.get("expected_all", []):
                asserts.append({"type": "icontains", "value": str(lit)})
            for lit in case.get("forbidden", []):
                asserts.append({"type": "not-icontains", "value": str(lit)})
            if not asserts:
                continue
            tests.append({
                "description": f"{case['id']} [{role}]",
                "vars": {"role": role, "prompt": task},
                "assert": asserts,
            })
    return {
        "# note": (
            "GENERATED by scripts/gen_promptfoo_config.py -- do not edit by hand.\n"
            "Providers carry no {{prompt}} placeholder: promptfoo appends the\n"
            "rendered prompt as the last argv element (finding W4). The bash\n"
            "runner (run_eval.sh) consumes the same catalogs directly."
        ),
        "defaultTest": {
            "options": {"provider": {"wrapping": False}},
        },
        "providers": PROVIDERS,
        "tests": tests,
    }


def main(argv: list[str]) -> int:
    check_only = "--check" in argv
    header = (
        "# GENERATED by scripts/gen_promptfoo_config.py -- DO NOT EDIT.\n"
        "# Source of truth: catalog.*.yaml next to this file.\n"
    )
    content = header + yaml.safe_dump(build(), sort_keys=False, allow_unicode=True, width=100)
    if check_only:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != content:
            print(f"[gen_promptfoo_config] {OUT} is stale -- regenerate.", file=sys.stderr)
            return 1
        print("[gen_promptfoo_config] up to date.")
        return 0
    OUT.write_text(content, encoding="utf-8")
    print(f"[gen_promptfoo_config] wrote {OUT} ({len(content.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
