#!/usr/bin/env python3
"""
validate-delegation.py — Validiert echte Viz-Event-Logs gegen erwartete Delegationsmuster.

Liest das ECHTE Viz-Log aus .meta-viz/events.jsonl (oder einem angegebenen Pfad)
und gleicht es gegen die in manual-scenarios.json definierten erwarteten
Delegationsketten ab.

Usage:
  python tests/manual/test-engine/validate-delegation.py --scenario SE-02
  python tests/manual/test-engine/validate-delegation.py --all
  python tests/manual/test-engine/validate-delegation.py --all --report
  python tests/manual/test-engine/validate-delegation.py --log .meta-viz/events.jsonl --scenario SE-02
"""

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent.parent  # tests/manual/test-engine/ → tests/manual/ → tests/ → repo-root
SCENARIOS_FILE = SCRIPT_DIR / "manual-scenarios.json"
DEFAULT_VIZ_LOG = REPO_ROOT / ".meta-viz" / "events.jsonl"
BUG_REPORTS_DIR = REPO_ROOT / "docs" / "bugs"


def detect_provider(events: list[dict]) -> str:
    """Detect which provider was used from agent_start events."""
    providers = set()
    for e in events:
        if e.get("event") == "agent_start":
            p = e.get("provider", "")
            if p:
                providers.add(p)
    if len(providers) == 1:
        return providers.pop()
    elif len(providers) > 1:
        return f"Multi ({', '.join(sorted(providers))})"
    return "Unknown"


def detect_target_repo(viz_log_path: Path) -> str:
    """Detect target repository from viz log path."""
    try:
        # Walk up from .meta-viz/events.jsonl to find repo root
        repo_root = viz_log_path.parent.parent
        # Check if this is agent-meta itself or a target project
        if (repo_root / ".meta-config" / "project.yaml").exists():
            return str(repo_root.name)
        return str(repo_root)
    except Exception:  # noqa: BLE001
        return "Unknown"


def generate_bug_report(result: dict, events: list[dict], scenario: dict, provider: str, repo: str) -> str:
    """Generate a standardized bug report for a failed test."""
    sid = result["id"]
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    failures = [r for r in result["results"] if r["status"] == "FAIL"]
    delegations = extract_delegations(events)

    lines = [
        f"# Bug Report: Test-FAIL {sid}",
        "",
        "> **Auto-generated by:** validate-delegation.py",
        f"> **Timestamp:** {timestamp}",
        f"> **Provider:** {provider}",
        f"> **Repository:** {repo}",
        f"> **Scenario:** {result['name']}",
        f"> **Status:** FAIL ({result['failed']}/{result['total']} checks failed)",
        "",
        "## User Prompt",
        "",
        '```',
        f"{scenario.get('user_input', 'N/A')}",
        '```',
        "",
        "## Expected Routing",
        "",
        "```",
    ]

    routing = scenario.get("expected_routing", {})
    if routing:
        lines.append(f"orchestrator -> {routing.get('to', '?')} (Intent: {routing.get('intent', '?')})")
    lines.append("```")
    lines.append("")
    lines.append("## Actual Delegations from Viz-Log")
    lines.append("")

    if delegations:
        lines.append("| # | From | To | Task |")
        lines.append("|---|------|-----|------|")
        for i, d in enumerate(delegations, 1):
            lines.append(f"| {i} | {d.get('from', '?')} | {d.get('to', '?')} | {d.get('task', '')[:40]} |")
    else:
        lines.append("*No delegate events found in log*")

    lines.extend([
        "",
        "## Failed Checks",
        "",
    ])

    for i, f in enumerate(failures, 1):
        expected = f.get("expected", "-")
        actual = f.get("actual", "-")
        detail = f.get("detail", "-")
        lines.append(f"{i}. **{f['check']}**")
        lines.append(f"   - Expected: `{expected}`")
        lines.append(f"   - Actual: `{actual}`")
        lines.append(f"   - Detail: {detail}")
        lines.append("")

    lines.extend([
        "## Provider-Specific Notes",
        "",
        f"- **Provider:** {provider}",
        f"- **Repository:** {repo}",
        "- This test was executed on the above provider. Behavior may differ on other providers.",
        "",
        "## Next Steps",
        "",
        "1. Review the orchestrator routing table in `agents/1-generic/orchestrator.md`",
        "2. Check if the intent classification logic handles this prompt correctly",
        "3. Verify provider-specific delegation patterns (FANOUT, PARALLEL_GROUP)",
        "4. Re-run on a different provider to determine if this is provider-specific",
        "",
        "## Delegation Report",
        "",
        "```",
        f"{result['summary']}",
        "```",
        "",
    ])

    return "\n".join(lines)


def parse_viz_log(log_path: Path) -> list[dict]:
    """Parse a viz event log file (JSONL)."""
    events = []
    if not log_path.exists():
        return events

    with open(log_path, "r", encoding="utf-8-sig") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                ev = json.loads(line)
                events.append(ev)
            except json.JSONDecodeError:
                continue
    return events


def extract_delegations(events: list[dict]) -> list[dict]:
    """Extract delegate events from log."""
    return [e for e in events if e.get("event") == "delegate"]


def extract_agent_events(events: list[dict]) -> dict[str, list[dict]]:
    """Group agent_start/end events by agent name."""
    by_agent: dict = {}
    for e in events:
        agent = e.get("agent", "")
        if not agent:
            continue
        if agent not in by_agent:
            by_agent[agent] = []
        by_agent[agent].append(e)
    return by_agent


SCENARIOS_SE_DIR = SCRIPT_DIR.parent / "scenarios" / "se"
SCENARIOS_FW_DIR = SCRIPT_DIR.parent / "scenarios" / "meta-agent"


def load_all_scenarios() -> dict:
    scenarios = {"SE": [], "FW": []}
    for f in sorted(SCENARIOS_SE_DIR.glob("*.json")):
        with open(f, "r", encoding="utf-8") as fh:
            scenarios["SE"].append(json.load(fh))
    for f in sorted(SCENARIOS_FW_DIR.glob("*.json")):
        with open(f, "r", encoding="utf-8") as fh:
            scenarios["FW"].append(json.load(fh))
    return {"scenarios": scenarios}


def find_scenario(scenario_id: str) -> dict | None:
    all_scenarios = load_all_scenarios()
    for group_data in all_scenarios["scenarios"].values():
        for s in group_data:
            if s["id"] == scenario_id:
                return s
    return None


def validate_scenario(scenario: dict, events: list[dict], strict: bool = False) -> dict:
    """Validate a single scenario against real viz log events."""
    scenario_id = scenario["id"]
    scenario_name = scenario["name"]
    expected_chain = scenario.get("delegation_chain", [])
    required_agents = scenario.get("required_agents", [])
    critical_checks = scenario.get("critical_checks", [])
    expected_routing = scenario.get("expected_routing", {})

    delegations = extract_delegations(events)
    agent_events = extract_agent_events(events)
    all_agents_in_log = set(agent_events.keys())

    results = []

    # 0. Check if log has any events
    if not events:
        results.append({
            "check": "Viz-Log vorhanden",
            "status": "FAIL",
            "detail": "Keine Events im Viz-Log gefunden. Wurde der Prompt eingegeben und die Session abgeschlossen?"
        })
        return {
            "id": scenario_id, "name": scenario_name,
            "total": 1, "passed": 0, "failed": 1,
            "success": False, "results": results,
            "summary": f"{scenario_id}: 0/1 passed, 1 failed -- FAIL"
        }

    # 1. Session start/end
    session_starts = [e for e in events if e.get("event") == "session_start"]
    session_ends = [e for e in events if e.get("event") == "session_end"]
    results.append({
        "check": "session_start vorhanden",
        "status": "PASS" if session_starts else "FAIL",
        "detail": f"{len(session_starts)} session_start events"
    })
    results.append({
        "check": "session_end vorhanden",
        "status": "PASS" if session_ends else "FAIL",
        "detail": f"{len(session_ends)} session_end events"
    })

    # 2. Orchestrator routing check (first delegation)
    if expected_routing:
        or_delegation = None
        for d in delegations:
            if d.get("from") == "orchestrator":
                or_delegation = d
                break

        if or_delegation:
            expected_to = expected_routing.get("to", "")
            actual_to = or_delegation.get("to", "")
            expected_intent = expected_routing.get("intent", "")

            routing_match = actual_to == expected_to

            results.append({
                "check": f"Routing: orchestrator -> {expected_to}",
                "status": "PASS" if routing_match else "FAIL",
                "expected": expected_to,
                "actual": actual_to,
                "detail": f"Intent: {expected_intent}" + ("" if routing_match else f" -- FALSCH: {actual_to}")
            })
        else:
            results.append({
                "check": f"Routing: orchestrator -> {expected_routing.get('to', '?')}",
                "status": "FAIL",
                "detail": "Kein orchestrator delegate-Event gefunden"
            })

    # 3. Delegation chain check
    actual_chain = [(d.get("from", ""), d.get("to", "")) for d in delegations]

    for i, expected_link in enumerate(expected_chain):
        expected_from = expected_link["from"]
        expected_to = expected_link["to"]
        note = expected_link.get("note", "")

        found = False
        for j, (af, at) in enumerate(actual_chain):
            if af == expected_from and at == expected_to:
                found = True
                actual_chain[j] = ("MATCHED", "MATCHED")
                break

        if found:
            results.append({
                "check": f"Delegation: {expected_from} -> {expected_to}",
                "status": "PASS",
                "detail": note if note else "Delegation gefunden"
            })
        else:
            results.append({
                "check": f"Delegation: {expected_from} -> {expected_to}",
                "status": "FAIL",
                "detail": f"Nicht gefunden: {expected_from} -> {expected_to} ({note})"
            })

    # 4. Strict order check
    if strict and expected_chain:
        order_correct = True
        prev_idx = -1
        for expected_link in expected_chain:
            found_at = -1
            for j, d in enumerate(delegations):
                if d.get("from") == expected_link["from"] and d.get("to") == expected_link["to"]:
                    found_at = j
                    break
            if found_at == -1 or found_at <= prev_idx:
                order_correct = False
                results.append({
                    "check": "Strikte Reihenfolge",
                    "status": "FAIL",
                    "detail": f"Delegation {expected_link['from']} -> {expected_link['to']} in falscher Reihenfolge"
                })
                break
            prev_idx = found_at

        if order_correct:
            results.append({
                "check": "Strikte Reihenfolge",
                "status": "PASS",
                "detail": "Alle Delegationen in korrekter Reihenfolge"
            })

    # 5. Required agents presence
    for agent in required_agents:
        present = agent in all_agents_in_log
        results.append({
            "check": f"Agent-Präsenz: {agent}",
            "status": "PASS" if present else "FAIL",
            "detail": "Im Log vorhanden" if present else "NICHT im Log"
        })

    # 6. Critical checks (manual verification hints)
    for check in critical_checks:
        # These are informational — we can't auto-verify all of them
        results.append({
            "check": f"Kritisch: {check[:60]}",
            "status": "INFO",
            "detail": "Manuell prüfen"
        })

    # Compute totals (INFO doesn't count as PASS or FAIL)
    total = sum(1 for r in results if r["status"] in ("PASS", "FAIL"))
    passed = sum(1 for r in results if r["status"] == "PASS")
    failed = sum(1 for r in results if r["status"] == "FAIL")

    return {
        "id": scenario_id,
        "name": scenario_name,
        "total": total,
        "passed": passed,
        "failed": failed,
        "success": failed == 0,
        "results": results,
        "summary": f"{scenario_id}: {passed}/{total} passed, {failed} failed -- {'PASS' if failed == 0 else 'FAIL'}"
    }


def render_report(all_results: list[dict], provider: str = "Unknown", repo: str = "Unknown") -> str:
    """Generate a Markdown report."""
    total_scenarios = len(all_results)
    passed_scenarios = sum(1 for r in all_results if r["success"])
    failed_scenarios = total_scenarios - passed_scenarios
    total_checks = sum(r["total"] for r in all_results)
    passed_checks = sum(r["passed"] for r in all_results)
    failed_checks = sum(r["failed"] for r in all_results)

    lines = [
        "# Delegations-Validierungs-Report",
        "",
        f"**Datum:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')} UTC",
        "**Quelle:** Echte Viz-Logs (.meta-viz/events.jsonl)",
        f"**Provider:** {provider}",
        f"**Repository:** {repo}",
        "",
        "## Zusammenfassung",
        "",
        "| Metrik | Wert |",
        "|--------|------|",
        f"| Szenarien | {total_scenarios} |",
        f"| Szenarien PASS | {passed_scenarios} |",
        f"| Szenarien FAIL | {failed_scenarios} |",
        f"| Checks Total | {total_checks} |",
        f"| Checks PASS | {passed_checks} |",
        f"| Checks FAIL | {failed_checks} |",
        f"| Provider | {provider} |",
        f"| Repository | {repo} |",
    ]
    if total_checks > 0:
        lines.append(f"| Erfolgsrate | {passed_checks/total_checks*100:.1f}% |")
    else:
        lines.append("| Erfolgsrate | N/A |")

    lines.extend([
        "",
        "## Szenario-Ergebnisse",
        "",
        "| Szenario | Name | Checks | Passed | Failed | Status |",
        "|----------|------|--------|--------|--------|--------|",
    ])

    for r in all_results:
        status_icon = "OK" if r["success"] else "FAIL"
        lines.append(f"| {r['id']} | {r['name'][:40]} | {r['total']} | {r['passed']} | {r['failed']} | {status_icon} |")

    lines.extend([
        "",
        "## Details",
        "",
    ])

    for r in all_results:
        status_str = "PASS" if r["success"] else "FAIL"
        lines.append(f"### {r['id']}: {r['name']} -- {status_str}")
        lines.append("")

        failures = [c for c in r["results"] if c["status"] == "FAIL"]
        passes = [c for c in r["results"] if c["status"] == "PASS"]

        if failures:
            lines.append("**Fehler:**")
            for i, f in enumerate(failures):
                expected = f.get("expected", "-")
                actual = f.get("actual", "-")
                detail = f.get("detail", "-")
                lines.append(f"- {i+1}. **{f['check']}**: Erwartet={expected}, Tatsächlich={actual} ({detail})")
            lines.append("")

        if passes:
            lines.append(f"**Bestanden ({len(passes)}):**")
            for p in passes[:10]:
                lines.append(f"- {p['check']}")
            if len(passes) > 10:
                lines.append(f"- ... und {len(passes)-10} weitere")
            lines.append("")

        if not failures:
            lines.append("Alle Checks bestanden.")
            lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Validate delegation patterns in REAL viz event logs")
    parser.add_argument("--scenario", default=None, help="Validate a single scenario (e.g. SE-02)")
    parser.add_argument("--all", action="store_true", help="Validate all scenarios (reads current viz log)")
    parser.add_argument("--strict", action="store_true", help="Strict order checking")
    parser.add_argument("--report", action="store_true", help="Generate Markdown report")
    parser.add_argument("--log", default=None, help="Path to viz log file (default: .meta-viz/events.jsonl)")
    parser.add_argument("--report-file", default=None, help="Write report to file")
    parser.add_argument("--auto-report-fail", action="store_true",
                        help="Auto-generate bug reports for failed scenarios")
    parser.add_argument("--target-repo", default=None,
                        help="Target repository path (for projects using agent-meta as submodule). "
                             "Viz log will be read from <repo>/.meta-viz/events.jsonl")

    args = parser.parse_args()

    # Determine log file
    if args.target_repo:
        log_path = Path(args.target_repo) / ".meta-viz" / "events.jsonl"
        repo_name = Path(args.target_repo).name
    else:
        log_path = Path(args.log) if args.log else DEFAULT_VIZ_LOG
        repo_name = detect_target_repo(log_path)

    events = parse_viz_log(log_path)
    provider = detect_provider(events)

    all_scenarios = load_all_scenarios()

    scenarios_to_validate = []

    if args.scenario:
        scenario = find_scenario(args.scenario)
        if scenario:
            scenarios_to_validate.append(scenario)
        else:
            print(f"  [!] Szenario '{args.scenario}' nicht gefunden")
            sys.exit(1)

    elif args.all:
        for group_data in all_scenarios["scenarios"].values():
            scenarios_to_validate.extend(group_data)

    if not scenarios_to_validate:
        print("  [!] Keine Szenarien zu validieren. Nutze --scenario oder --all")
        sys.exit(1)

    if not events:
        print(f"  [!] Keine Events im Viz-Log: {log_path}")
        print("      Stelle sicher dass:")
        print("      1. Viz aktiviert ist: viz.enabled=true in .meta-config/project.yaml")
        print("      2. Ein Prompt eingegeben und die Session abgeschlossen wurde")
        print("      3. Das Verzeichnis .meta-viz/ existiert")
        if args.target_repo:
            print(f"      4. Ziel-Repo korrekt angegeben: --target-repo={args.target_repo}")
        sys.exit(1)

    print(f"\n  {'='*60}")
    print("  DELEGATIONS-VALIDIERUNG")
    print(f"  {'='*60}")
    print(f"  Repository:  {repo_name}")
    print(f"  Provider:    {provider}")
    print(f"  Viz-Log:     {log_path}")
    print(f"  Events:      {len(events)}")
    print(f"  Szenarien:   {len(scenarios_to_validate)}")
    print(f"  {'='*60}\n")

    all_results = []
    failed_results = []

    for scenario in scenarios_to_validate:
        result = validate_scenario(scenario, events, strict=args.strict)
        all_results.append(result)

        if not result["success"]:
            failed_results.append((scenario, result))

        status_icon = "[OK]" if result["success"] else "[!!]"
        print(f"  {status_icon} {result['summary']}")

        if not result["success"]:
            for r in result["results"]:
                if r["status"] == "FAIL":
                    detail = r.get('detail', '?').replace('\u2192', '->')
                    check_name = r['check'].replace('\u2192', '->')
                    print(f"    !! {check_name}: {detail}")

    # Auto-generate bug reports for failures
    if args.auto_report_fail and failed_results:
        BUG_REPORTS_DIR.mkdir(parents=True, exist_ok=True)
        print("\n  [i] Auto-Report aktiviert — generiere Bug-Reports...")
        for scenario, result in failed_results:
            bug_report = generate_bug_report(result, events, scenario, provider, repo_name)
            bug_file = BUG_REPORTS_DIR / f"bug-{result['id']}-{provider}-{datetime.now(timezone.utc).strftime('%Y%m%d-%H%M%S')}.md"
            bug_file.write_text(bug_report, encoding="utf-8")
            print(f"  [i] Bug-Report: {bug_file.name}")
            print("      Tipp: Führe aus um als GitHub Issue einzureichen:")
            print(f"      python scripts/feedback.py --bug {bug_file}")

    # Report
    if args.report and all_results:
        report = render_report(all_results, provider=provider, repo=repo_name)

        if args.report_file:
            Path(args.report_file).write_text(report, encoding="utf-8")
            print(f"\n  [i] Report gespeichert: {args.report_file}")
        else:
            report_path = SCRIPT_DIR / "delegation-report.md"
            report_path.write_text(report, encoding="utf-8")
            print(f"\n  [i] Report gespeichert: {report_path}")

    # Summary
    total = len(all_results)
    passed = sum(1 for r in all_results if r["success"])
    print(f"\n  {'='*60}")
    print(f"  ERGEBNIS: {passed}/{total} Szenarien PASS")
    if passed < total:
        print(f"  {total - passed} FAIL(s) — Bug-Reports in: {BUG_REPORTS_DIR}")
    print(f"  Provider:  {provider}")
    print(f"  Repository: {repo_name}")
    print(f"  {'='*60}")


if __name__ == "__main__":
    main()
